export const names = [
  "Canapé 3 places",
  "Machine à laver",
  "Vélo d'appartement",
  "Table de salle à manger",
  "Réfrigérateur",
  "Ordinateur portable",
  "Télévision LED",
  "Armoire penderie",
  "Lave-vaisselle",
  "Matelas double",
  "Bibliothèque en bois",
  "Chaise de bureau",
  "Micro-ondes",
  "Aspirateur",
  "Commode",
  "Planche à repasser",
  "Ventilateur sur pied",
  "Four électrique",
  "Étagères murales",
  "Machine à coudre"
];

export const descriptors = [
  "en très bon état, peu utilisé",
  "quelques traces d'usure mais fonctionnel",
  "excellent état, comme neuf",
  "bon état général, bien entretenu",
  "état correct, quelques rayures superficielles",
  "très bon état, utilisé avec soin",
  "parfait état de marche",
  "légers signes d'usage mais solide",
  "bon fonctionnement, aspect vieilli",
  "état impeccable, jamais servi",
  "quelques défauts esthétiques mineurs",
  "très propre, bien conservé",
  "fonctionne parfaitement, design vintage",
  "excellent état, garantie encore valable",
  "bon état d'usage, petites marques normales",
  "état neuf, emballage d'origine",
  "bien maintenu, prêt à servir",
  "quelques éraflures mais très fonctionnel",
  "parfait pour dépannage, état moyen",
  "comme sorti du magasin"
];

export const types = [
  "Électroménager",
  "Mobilier",
  "Informatique",
  "Décoration",
  "Sport & Loisirs",
  "Vêtements",
  "Livres & Médias",
  "Jardin & Bricolage",
  "Cuisine & Vaisselle",
  "Jouets & Enfants",
  "Électronique",
  "Literie",
  "Salle de bain",
  "Bureau & Papeterie",
  "Art & Collection",
  "Musique & Instruments",
  "Automobile",
  "Maison & Entretien",
  "Santé & Bien-être",
  "Animaux"
];